# Generated by Django 4.0.4 on 2022-05-02 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_nacimiento', models.DateField(verbose_name=datetime.date(2022, 5, 2))),
            ],
        ),
    ]
