# Generated by Django 4.0.4 on 2022-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='profesor',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
