# Generated by Django 4.0.4 on 2022-05-19 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_remove_comentario_profesor_comentario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('duracion', models.IntegerField()),
                ('precio', models.FloatField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.profesor')),
            ],
        ),
    ]
