# Generated by Django 4.0.4 on 2022-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_alter_curso_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ManyToManyField(related_name='cursos', to='english.profesor'),
        ),
    ]
