# Generated by Django 4.0.4 on 2022-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0008_remove_curso_profesor_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(),
        ),
    ]
